# Generated by Django 3.1.6 on 2021-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=255)),
                ('mdate', models.DateField(default='')),
                ('mtime', models.TimeField(default='')),
                ('deadline', models.DateTimeField(default='')),
            ],
        ),
    ]
